application.security.jwt.secret-key = eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNzc4MjE3OCwiaWF0IjoxNzI3NzgyMTc4fQqmJhX6pbrpz6h9fnSLcyaXG4uponZnlmOg6UzQ7aYw
application.security.jwt.expiration = 86400000

application.file.upload.images-output-path = ./uploads

#file.upload-dir=C:\\

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devspaceservice@gmail.com
spring.mail.password=pulg wspp qski hhym
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

domain.address=http://localhost:8085


